// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(TimeishContext))]
    [Migration("20181004192952_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<int>("Hours");

                    b.Property<int?>("TimesheetId");

                    b.HasKey("Id");

                    b.HasIndex("TimesheetId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("api.Models.PayPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("End");

                    b.Property<DateTime>("Start");

                    b.HasKey("Id");

                    b.ToTable("PayPeriod");
                });

            modelBuilder.Entity("api.Models.Timesheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Approved");

                    b.Property<string>("EmployeeName");

                    b.Property<DateTime>("Issued");

                    b.Property<int?>("PayPeriodId");

                    b.Property<DateTime>("Submitted");

                    b.HasKey("Id");

                    b.HasIndex("PayPeriodId");

                    b.ToTable("Timesheets");
                });

            modelBuilder.Entity("api.Models.Activity", b =>
                {
                    b.HasOne("api.Models.Timesheet", "Timesheet")
                        .WithMany("Activities")
                        .HasForeignKey("TimesheetId");
                });

            modelBuilder.Entity("api.Models.Timesheet", b =>
                {
                    b.HasOne("api.Models.PayPeriod", "PayPeriod")
                        .WithMany("Timesheets")
                        .HasForeignKey("PayPeriodId");
                });
#pragma warning restore 612, 618
        }
    }
}
